### ISSUE TITLE
project search throws error

### ISSUE THREAD

**Issue by jdeck88** [biocodellc/biocode-lims#92]
pulled latest and then ran geneious from gradle...
tried the project search, project contains "BALI" and got the following response:

com.biomatters.geneious.publicapi.databaseservice.DatabaseServiceException: Server returned an error: Unknown Column: Project

Cause: com.biomatters.geneious.publicapi.databaseservice.DatabaseServiceException: Server returned an error: Unknown Column: Project com.biomatters.plugins.biocode.labbench.ConnectionException at com.biomatters.plugins.biocode.labbench.fims.geome.geomeFIMSConnection.getTissueIdsMatchingQuery(geomeFIMSConnection.java:183) at com.biomatters.plugins.biocode.labbench.BiocodeService.retrieve(BiocodeService.java:779) at com.biomatters.plugins.biocode.labbench.BiocodeService.retrieve(BiocodeService.java:730) at com.biomatters.plugins.biocode.labbench.BiocodeService.retrieve(BiocodeService.java:726) at com.biomatters.iseek.databasepanel.p.a(DatabaseServiceDocumentList.java:310) at com.biomatters.iseek.databasepanel.ae.a(DatabaseServiceModel.java:111) at et.run(Task.java:85) at java.lang.Thread.run(Thread.java:748) Caused by: com.biomatters.geneious.publicapi.databaseservice.DatabaseServiceException: Server returned an error: Unknown Column: Project at com.biomatters.plugins.biocode.labbench.fims.geome.geomeFIMSClient.getRestServiceResult(geomeFIMSClient.java:118) at com.biomatters.plugins.biocode.labbench.fims.geome.geomeFIMSConnection.getTissueIdsMatchingQuery(geomeFIMSConnection.java:176) ... 7 more Caused by: javax.ws.rs.WebApplicationException: ... 9 more

**Comment by jdeck88** [comment]
duplicate of #88
