### ISSUE TITLE
Tests failing when running biocode-lims [test]

### ISSUE THREAD

**Issue by jdeck88** [biocodellc/biocode-lims#96]
The following 9 tests fail when running biocode-lims [test] gradle task:

![image](https://user-images.githubusercontent.com/1154501/45005823-6ba3d400-afaa-11e8-8c04-0d8d80b9b364.png)

The stack trace on all of these tests:
java.lang.reflect.InvocationTargetException
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at com.biomatters.geneious.publicapi.utilities.ThreadUtilities.invokeNowOrWait(ThreadUtilities.java:63)
	at com.biomatters.plugins.biocode.labbench.NewPlateDocumentOperation._performOperation(NewPlateDocumentOperation.java:125)
	at com.biomatters.plugins.biocode.labbench.NewPlateDocumentOperationTest.createPlateUsingOptions(NewPlateDocumentOperationTest.java:234)
	at com.biomatters.plugins.biocode.labbench.NewPlateDocumentOperationTest.createPlate(NewPlateDocumentOperationTest.java:230)
	at com.biomatters.plugins.biocode.labbench.NewPlateDocumentOperationTest.createPlate(NewPlateDocumentOperationTest.java:219)
	at com.biomatters.plugins.biocode.labbench.NewPlateDocumentOperationTest.testCreateStripExtractionPlateFromStripExtractionPlate(NewPlateDocumentOperationTest.java:43)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.runTestClass(JUnitTestClassExecuter.java:114)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.execute(JUnitTestClassExecuter.java:57)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassProcessor.processTestClass(JUnitTestClassProcessor.java:66)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:51)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:32)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
	at com.sun.proxy.$Proxy2.processTestClass(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:109)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:147)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:129)
	at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:404)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
	at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:46)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.reflect.InvocationTargetException
	at org.virion.jam.util.Utils.invokeAndWait(Utils.java:151)
	at com.biomatters.geneious.publicapi.utilities.ThreadUtilities.invokeAndWait(ThreadUtilities.java:91)
	at com.biomatters.geneious.publicapi.utilities.ThreadUtilities.invokeNowOrWait(ThreadUtilities.java:56)
	... 52 more
Caused by: java.lang.IllegalArgumentException: Key too long: buttonVisibleView/Add Thermocycles:Create new Thermocycles, or view existing ones
	at java.util.prefs.AbstractPreferences.put(AbstractPreferences.java:243)
	at java.util.prefs.AbstractPreferences.putBoolean(AbstractPreferences.java:470)
	at com.biomatters.geneious.publicapi.components.GeneiousActionToolbar.addComponent(GeneiousActionToolbar.java:735)
	at com.biomatters.geneious.publicapi.components.GeneiousActionToolbar.addButton(GeneiousActionToolbar.java:715)
	at com.biomatters.geneious.publicapi.components.GeneiousActionToolbar.addAction(GeneiousActionToolbar.java:625)
	at com.biomatters.geneious.publicapi.components.GeneiousActionToolbar.addAction(GeneiousActionToolbar.java:611)
	at com.biomatters.geneious.publicapi.components.GeneiousActionToolbar.addAction(GeneiousActionToolbar.java:599)
	at com.biomatters.plugins.biocode.labbench.plates.PlateViewer.init(PlateViewer.java:173)
	at com.biomatters.plugins.biocode.labbench.plates.PlateViewer.<init>(PlateViewer.java:49)
	at com.biomatters.plugins.biocode.labbench.NewPlateDocumentOperation$1.run(NewPlateDocumentOperation.java:112)
	at org.virion.jam.util.Utils$1.run(Utils.java:130)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:301)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by jdeck88** [comment]
fixed with release release v3.0.7
